#!/bin/bash

# introduced grep filters to ignore differences between win and mingw
Contour_test 2>&1 | grep -v SContneval | grep -v 'Summary of statistics'

# cat Contour_test.{2D,2Dborder,3D,3Dborder,m}
cat Contour_test.{2D,2Dborder,m} | perl -ne 'binmode(STDOUT); print unless /^Vertex (\d+) / && $1=~/^(9|29|37|151|13|31|185|188|7|70|72|74|86|131|168|205|246|252|260|266)$/ || /^Face /;'
# grep -v "^Face" | grep -v "Vertex 9 " | grep -v "Vertex 29 " | grep -v "Vertex 37 " | grep -v "Vertex 151 " | grep -v "Vertex 13 " | grep -v "Vertex 31 " | grep -v "Vertex 185 " | grep -v "Vertex 188 "

rm  Contour_test.{2D,2Dborder,3D,3Dborder,m}
