#!/bin/bash

# Added because Image_test on mingw sometimes gets stuck in busy-wait for Image_test.
# Just opening the process's properties in Process Explorer releases the wait, somehow.
# Instead, the problem goes away if I test the small grid size against g_ompthresh.
# It appears that running OMP parallel_for...() on work that is too small
#  can cause program to stop responding under mingw.
# export OMP_NUM_THREADS=1

Image_test
