#!/bin/bash

# was: (tTimer <$nul |& ...)
# (tTimer |& grep -v 'Timing on' | sed -e 's/^/TEST>> /' -e 's/[0-9]\.[0-9]*//g')
# (tTimer |& tee tTimer.raw | grep -v 'Timing on' | sed -e 's/^/TEST>> /' -e 's/[0-9]\.[0-9].*$//')
# (tTimer |& grep -v 'Summary of timers' | grep -v 'Timing on' | sed -e 's/^/TEST>> /' -e 's/[0-9]\.[0-9].*$//')

tTimer |& grep -v 'Summary of timers' | grep -v 'Timing on' | perl -pe 'binmode(STDOUT); s/[0-9]\.[0-9].*$//'
