#!/bin/bash

# was: (tTimer <$nul 2>&1 | ...)
# (tTimer 2>&1 | grep -v 'Timing on' | sed -e 's/^/TEST>> /' -e 's/[0-9]\.[0-9]*//g')
# (tTimer 2>&1 | tee tTimer.raw | grep -v 'Timing on' | sed -e 's/^/TEST>> /' -e 's/[0-9]\.[0-9].*$//')
# (tTimer 2>&1 | grep -v 'Summary of timers' | grep -v 'Timing on' | sed -e 's/^/TEST>> /' -e 's/[0-9]\.[0-9].*$//')

tTimer 2>&1 | grep -v 'Summary of timers' | grep -v 'Timing on' | perl -pe 'binmode(STDOUT); s/[0-9]\.[0-9].*$//'
