#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

a=(
  data/cactus.recon.m
  data/cactus.opt.m
  data/cactus.sub0.m
  data/cactus.sub2limit.m
  data/distcap.recon.m
  data/distcap.opt.m
  data/distcap.sub0.m
  data/distcap.sub2limit.m
  data/curve1.opt.a3d
  data/curve1.joined.a3d
  data/curve1.recon.a3d
  data/blob5.meshopt.simplified.m
  data/gaudipark.orig.m
  data/gaudipark.pm
  data/cessna.pm
  data/club.pm
  data/club.nf1000.m
  data/standingblob.geomorphs
  data/standingblob.nf20000.ohull.pm
  data/office.nf80000.orig.m
  data/office.nf80000.sr.pm
  data/gcanyon_sq200.orig.m
  data/gcanyon_sq200.pm
  data/gcanyon_sq129_b44.l-1.stitched.pm
  data/gcanyon_sq129_b44.l0.stitched.pm
  data/gcanyon_sq129_b44.l1.stitched.pm
  data/gcanyon_sq129_b44.l1.stitched.new.base.m
  data/gcanyon_sq129_b44.l1t.stitched.pm
  data/gcanyon_sq129_b44.l2.pm
  data/create_terrain_hierarchy.log
  data/office.nf200000.mincycles.m
  data/bunny.vertexcache.m
  data/bunny.sphparam.m
  data/octaflat_eg128.uv.sphparam.m
  data/bunny.spheresample.remesh.m
  data/bunny.spheresample.octaflat.unrotated.normalmap.png
  data/bunny.lonlat.unrotated.normalmap.png
  data/bunny.split_meridian.pm
  data/mechpart.image.bmp
  data/mechpart.video.mp4
  data/mechpart.hlr.ps
  data/texture.output.png
)
rm -f "${a[@]}"
