MeshRoot = ..
include $(MeshRoot)/make/Makefile_prog

# b 'make -C ~/git/mesh_processing/SphereParam SphereParam.s'  # Does not need the next line.
# SphereParam.$(extobj): cxxall += $(cxx_list_assembly_code)
